dist: trusty

language: python

python:
  - 3.8

install:
  # install the package
  - pip install -U pip
  - pip install --progress-bar off -r requirements.txt
  - pip install --progress-bar off -r dev_requirements.txt
  - pip install .

script:
  # test import
  - python -c "import spatialOmics"

jobs:
  include:
    - stage: Documentation
      python: 3.8
      script:
        # build documentation pages
        - cd docs && make html && cd ..
      deploy:
        - provider: pages
          skip_cleanup: true
          github_token: $GITHUB_TOKEN
          # Set in the settings page of your repository, as a secure variable
          # see https://docs.travis-ci.com/user/deployment/pages/#setting-the-github-token
          local_dir: docs/_build/html
          github_url: github.com
          repo: AI4SCR/spatial-omics
          on:
            branch: master

notifications:
  slack:
    rooms:
      - ibm-research:82jY54xYQAiJOqZ2ycRDM4jo
    on_success: always
    on_failure: always
